package com.google.launchpod.data;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.google.appengine.api.datastore.Entity;
import com.google.launchpod.servlets.FormHandlerServlet;

@JacksonXmlRootElement(namespace = "version\"2.0\"", localName = "rss")
public final class UserFeed{

  @JacksonXmlElementWrapper
  private final String channel = "";

  @JacksonXmlProperty(localName = "title")
  private final String channelTitle = "Launchpod RSS Feed";

  @JacksonXmlProperty(localName = "link")
  private final String channelLink = "https://launchpod-step18-2020.appspot.com";

  @JacksonXmlProperty(localName = "description")
  private final String channelDescription = "Feed generated in the launchpod website";

  @JacksonXmlElementWrapper
  private final String item = "";

  @JacksonXmlProperty
  public final String podcastTitle;

  @JacksonXmlProperty
  private final String link;

  @JacksonXmlProperty
  private final String language = "en";

  @JacksonXmlProperty
  private final String description = "New episode generated by launchpod website";

  @JacksonXmlProperty
  private final String pubDate;

  private final String email;
  private final long timestamp;

  private UserFeed(String podcastTitle, String email, String mp3Link, long timestamp, String pubDate) {
    this.podcastTitle = podcastTitle;
    this.email = email;
    this.link = mp3Link;
    this.timestamp = timestamp;
    this.pubDate = pubDate;
  }
  /** Create UserFeed Object from Entity
   *  @param entity : entity that is being used to create user feed object
   *  @return UserFeed object
   */
  public static UserFeed fromEntity(Entity entity){
    String podcastTitle = (String) entity.getProperty(FormHandlerServlet.PODCAST_TITLE);
    String email = (String) entity.getProperty(FormHandlerServlet.EMAIL);
    String mp3Link = (String) entity.getProperty(FormHandlerServlet.MP3LINK);
    long timestamp = (long) entity.getProperty(FormHandlerServlet.TIMESTAMP);
    String pubDate = (String) entity.getProperty(FormHandlerServlet.PUB_DATE);

    return new UserFeed(podcastTitle, email, mp3Link, timestamp, pubDate);
  }
}
